#The Story Engine
engines = {}
conflicts = {}
aspects = {}
anchors = {}
agents = {}

#The Deck of Worlds
regions = {}
landmarks = {}
namesakes = {}
attributes = {}
origins = {}
advents = {}

#Lore Master's Deck
agents_traits = {}
agents_backgrounds = {}
agents_agendas = {}
agents_namesakes = {}
factions = {}
factions_traits = {}
factions_backgrouns = {}
factions_agendas = {}
factions_namesakes = {}
events = {}
events_traits = {}
events_catalyst = {}
events_fallout = {}
events_namesakes = {}
locations = {}
locations_traits = {}
locations_backgrounds = {}
locations_namesakes = {}
objects = {}
objects_traits = {}
objects_backgrounds = {}
objects_namesakes = {}
materials = {}
materials_traits = {}
materials_backgrounds = {}
materials_namesakes = {}
creatures = {}
creatures_traits = {}
creatures_backgrounds = {}
creatures_namesakes = {}
deities = {}
deities_traits = {}
deities_backgrounds = {}
deities_domains = {}
deities_agendas = {}
modifiers = {}
